# Site Settings
title: Teras Sukaratu
tagline: SUKARATU
email: your-email@domain.com
description: >
  Desa Sukaratu merupakan sebuah desa yang berada di wilayah Kecamatan Darmaraja. Wilayah Desa Sukaratu berdekatan dengan pusat Kecamatan Darmaraja, jika dilihat dari Alun-alun Darmaraja, posisinya berada di sebelah timur laut. Sementara jarak pusat desa dengan pusat Kecamatan Darmaraja sekitar 1 km
baseurl: "/mere-blog-theme"
url: "https://sukaratu.org"
permalink: pretty
force_theme: light

paginate: 6
paginate_path: "/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: /img/home.jpg
      show_sidebar: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

collections:
  authors:
    output: true
